"""add fields to user

Revision ID: 354ea76da963
Revises: 6cfb96031044
Create Date: 2019-02-19 11:43:53.877677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354ea76da963'
down_revision = '6cfb96031044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    # ### end Alembic commands ###
